In [16]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import time
import openpyxl
from konlpy.tag import Okt
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
#dr=webdriver.Chrome()                                                                                                                          


In [17]:
horse_list=pd.read_csv("../Data/horse_list.csv")
horse_list[horse_list.iloc[:,1]=="가왕신화"]

Unnamed: 0     0
1593        1593  가왕신화

In [19]:
len(horse_list)

2003

In [28]:
horse_list=pd.read_csv("../Data/horse_list.csv")
horse_list=horse_list['0'].to_numpy()
horse_list[0:300]

array(['무대바람', '마의질주', '쾌속비행', '포르티우스', '광명일호', '달천', '제주제왕', '월드트레인',
       '보금산', '예스맨', '바람기억', '명문군단', '바다여왕', '대지일호', '무패질주', '기적바람', '반전',
       '장엄', '회색등불', '포인트', '불빛영웅', '푸른물결', '함지박', '장백천지', '황룡전설', '금빛열매',
       '찬란한꿈', '환희타임', '일대강자', '칸의제왕', '여왕하트', '삼다지존', '번개왕자', '백만장자',
       '백호신천', '군자삼락', '원당봉', '동부여걸', '태왕별', '시무상', '한라왕후', '으뜸공신',
       '특등대부', '장타명성', '카라', '국내성', '천년바위', '꼬마대군', '천사표', '충용비마', '청금세상',
       '사자황', '청초호', '봉성여신', '생각대로', '사랑가득', '불사요정', '황금가면', '남도비행',
       '서귀명가', '진출행', '일류무대', '웅진명성', '일사십리', '가야탄생', '광아의보스', '삼다소식',
       '용설란', '중문여제', '백점여왕', '천중천', '남풍전력', '특기생', '월출', '광아의전설', '소확행',
       '달의찬가', '도시체험', '오라대장', '삼다히어로', '달빛요정', '커리어', '청마대선', '신촌길',
       '황금구슬', '신촌로', '저스트원', '성읍세상', '백년친구', '미래제주', '남단여제', '섬문화',
       '불멸의힘', '아라신화', '영웅군단', '호승고을', '혈기방장', '무한가속', '가거도', '장전보배',
       '계림미소', '금빛모래', '삼다비행', '금사자', '유랑별', '태산여왕', '진성여왕', '한라고원',
       '백호번개', '풍류예찬', '앵커링', '참매', '일출정복', '이쁜이', '햇살처럼', '두루', '강력추천',


In [20]:
url = "https://race.kra.co.kr/racehorse/ProfileHorsenameKinds.do?Act=08&Sub=1&meet=2"

response = requests.get(url,headers={'User-agent':'Mozilla/5.0'})

In [78]:

driver = webdriver.Chrome("C:/Users/wjswp/Desktop/chromedriver-win64/chromedriver-win64/chromedriver.exe")
driver.get('https://race.kra.co.kr/racehorse/ProfileHorsenameKinds.do?Act=08&Sub=1&meet=2')
buy=[]
sicks=[]
ranks=[]
horse_items=[]
dad_record = []
dad_rate = []
mom_record = []
mom_rate=[]
horse_rating=[]
horse_meter=[]

for horse in horse_list[1501:len(horse_list)]:
    driver.get('https://race.kra.co.kr/racehorse/ProfileHorsenameKinds.do?Act=08&Sub=1&meet=2')
    driver.find_element(By.ID,'searchHorseName').send_keys(horse)
    driver.find_element(By.CLASS_NAME,'btnType4.case').click()
    driver.find_element(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[2]/a').click()

    #최초도입가 텍스트 추출
    try:
        buy.append(driver.find_element(By.XPATH,'//*[@id="contents"]/div[1]/table/tbody/tr[12]/td[1]').text)
    except:
        buy.append(driver.find_element(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr[12]/td[1]').text)


    #진료사항 탭 들어간 이후 질병날짜(sick_date),질병사항(sick_name) 추출
    driver.find_element(By.XPATH,'//*[@id="contents"]/ul/li[5]/a').click()
    buttons=driver.find_elements(By.XPATH,'//*[@id="contents"]/p[2]/a')
    sick = []
    for i in range(len(buttons)):
        driver.find_element(By.XPATH,f'//*[@id="contents"]/p[2]/a[{i+1}]').click()
        hospitals=driver.find_elements(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[2]')
        for i in range(1,len(hospitals)+1):
            sick_date=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[2]').text
            sick_name=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[4]').text
            sick.append(sick_name+' '+sick_date)
    sicks.append(sick)

    #등급변동 정보
    driver.find_element(By.XPATH,'//*[@id="contents"]/ul/li[7]/a').click()

    rank_dates=driver.find_elements(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[3]')
    rank = []
    for i in range(1,len(rank_dates)+1):
        rank_name=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[3]').text
        rank_date=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[4]').text
        rank.append(rank_name+' '+rank_date)
    ranks.append(rank)

    #승인장구 정보
    driver.find_element(By.XPATH,'//*[@id="contents"]/ul/li[12]/a').click()

    items=driver.find_elements(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[3]')
    item = []
    for i in range(1,len(items)+1):
        name=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[1]').text
        start_date=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[2]').text
        end_date=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[3]').text
        item.append(name+' '+start_date+'~'+end_date)
    horse_items.append(item)

    #레이팅
    driver.find_element(By.XPATH,'//*[@id="contents"]/ul/li[3]/a').click()
    ratings=driver.find_elements(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[2]/a')
    rating=[]
    for i in range(1,len(ratings)+1):
        date=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[2]').text
        rating_=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[10]').text
        rating.append(date+' '+rating_)
    horse_rating.append(rating)

    #거리별기록
    driver.find_element(By.XPATH,'//*[@id="contents"]/ul/li[8]/a').click()
    meter=[]
    meters=driver.find_elements(By.XPATH,'//*[@id="contents"]/div[2]/table/tbody/tr/td[1]')
    print(len(meters))
    try:
        for i in range(1,len(meters)+1):
            distance=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/th[1]').text
            first_rate=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[2]').text
            second_rate=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[3]').text
            third_rate=driver.find_element(By.XPATH,f'//*[@id="contents"]/div[2]/table/tbody/tr[{i}]/td[4]').text
            meter.append(distance+' '+first_rate+' '+second_rate+' '+third_rate)
    except:
        distance.append("None")
        first_rate.append("None")
        second_rate.append("None")
        third_rate.append("None")
        meter.append(distance+' '+first_rate+' '+second_rate+' '+third_rate)
    horse_meter.append(meter)


    #부 정보
    driver.back()
    try:
        driver.find_element(By.XPATH, '//*[@id="contents"]/ul/li[11]/a').click()
        driver.find_element(By.XPATH, '//*[@id="contents"]/table[3]/tbody/tr/td[1]/a[2]').click()
        dad_record.append(driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/table/tbody/tr[5]/td[1]').text)
        dad_rate.append(driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/table/tbody/tr[5]/td[2]').text)
    except:
        dad_record.append("None")
        dad_rate.append("None")

    #모 정보
    driver.back()
    driver.back()
    try:
        driver.find_element(By.XPATH, '//*[@id="contents"]/ul/li[11]/a').click()
        driver.find_element(By.XPATH, '//*[@id="contents"]/table[3]/tbody/tr/td[2]/a[2]').click()
        mom_record.append(driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/table/tbody/tr[5]/td[1]').text)
        mom_rate.append(driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/table/tbody/tr[5]/td[2]').text)
    except:
        mom_record.append("None")
        mom_rate.append("None")


driver.quit()


data = {
    'ini_price' :buy,
    'sicks' : sicks,
    'ranks' : ranks,
    'horse_items' : horse_items,
    'dad_record' : dad_record,
    'dad_rate' : dad_rate,
    'mom_record' : mom_record,
    'mom_rate' : mom_rate,
    'horse_rate' : horse_rating,
    'horse_meter' : horse_meter
}
pd.DataFrame(data)
pd.DataFrame(data).to_excel('1501~마종데이터2.xls',index=False)


C:\Users\wjswp\AppData\Local\Temp\ipykernel_8372\4147602405.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome("C:/Users/wjswp/Desktop/chromedriver-win64/chromedriver-win64/chromedriver.exe")


5
1
3
3
3
2
2
2
1
4
3
1
4
2
1
3
4
5
4
4
1
3
1
5
3
5
2
4
6
1


AttributeError: 'str' object has no attribute 'append'

In [39]:
data = {
    'ini_price' :buy,
    'sicks' : sicks,
    'ranks' : ranks,
    'horse_items' : horse_items,
    'dad_record' : dad_record,
    'dad_rate' : dad_rate,
    'mom_record' : mom_record,
    'mom_rate' : mom_rate
}
pd.DataFrame(data)

ini_price                                              sicks  \
0                  [좌전지파행 2020/08/15, 좌전지파행 2020/08/14, 운동기질환 기타 ...   
1                  [정치 2017/08/12, 낭치 2017/08/12, 일본뇌염예방접종 2017/0...   
2                  [정치 2019/04/03, 식이성 식욕부진 2016/09/04, 정치 2016/0...   
3                  [운동기인성 피로회복 2019/12/20, 좌각막염 2019/12/14, 좌각막염 ...   
4    10,000천원(개별)  [운동기질환 기타 2019/05/26, 운동기질환 기타 2019/05/25, 운동기...   
..            ...                                                ...   
295                [운동기질환 기타 2019/11/30, 운동기질환 기타 2019/10/06, 운동기...   
296                [양전지파행 2018/10/19, 양전지파행 2018/09/20, 양전지파행 201...   
297                [좌전지파행 2023/04/23, 좌전지파행 2022/12/22, 좌전지파행 202...   
298                [술후처치(거세술) 2017/11/29, 술후처치(거세술) 2017/11/27, 거...   
299                [운동기질환 기타 2017/03/12, 감기 2015/10/12, 기타임신검사(초음...   

                                                 ranks  \
0    [제4 2020/01/01 ~ 2021/05/12, 제3 2019/08/04 ~ 2...   
1    [제5 2020/01/01 ~ 2020/05/07, 제4 2018/09/02 ~ 2...   
2    [제3 2020/08/23 ~ 2021/01/27, 제4 2020/01/01 ~ 2...   
3    [제4 2018/08/26 ~ 2020/07/22, 제1 2016/08/19 ~ 2...   
4    [제4 2022/01/01 ~ 2023/04/20, 제3 2021/09/12 ~ 2...   
..                                                 ...   
295  [제1 2018/09/09 ~ 2020/11/05, 제2 2018/08/26 ~ 2...   
296  [제4 2020/01/01 ~ 2020/07/22, 제3 2019/01/20 ~ 2...   
297  [제3 2020/06/28 ~ 현재, 제4 2020/01/01 ~ 2020/06/2...   
298  [제4 2018/08/26 ~ 2021/11/13, 제1 2017/09/30 ~ 2...   
299  [제4 2018/08/26 ~ 2019/03/03, 제1 2015/11/06 ~ 2...   

                                           horse_items        dad_record  \
0                                    [눈가면 2018/02/25~]   42전 (6/8/5/7/5)   
1       [눈가면 2020/02/02~, 구각자극판 2019/05/14~2019/11/24]    2전 (2/0/0/0/0)   
2    [눈가면 2017/12/03~2019/01/27, 눈가면 2016/08/21~201...   42전 (6/8/5/7/5)   
3                                    [눈가면 2017/04/09~]              None   
4              [계란형큰고리재갈 2021/05/02~, 눈가면 2018/06/24~]              None   
..                                                 ...               ...   
295                                  [눈가면 2019/09/01~]              None   
296                                  [눈가면 2015/07/12~]    2전 (2/0/0/0/0)   
297  [망사눈가면 2023/08/20~, 망사눈가면 2022/09/30~2023/03/1...  55전 (7/6/10/6/6)   
298  [망사눈가면 2019/09/01~2020/11/15, 눈가면 2017/09/24~2...   45전 (3/6/5/9/8)   
299                      [망사눈가면 2015/11/01~2016/03/06]              None   

                                          dad_rate       mom_record  \
0       단승 : 14.3%      복승 : 33.3%      연승 : 45.2%   0전 (0/0/0/0/0)   
1    단승 : 100.0%      복승 : 100.0%      연승 : 100.0%             None   
2       단승 : 14.3%      복승 : 33.3%      연승 : 45.2%  18전 (5/4/2/2/1)   
3                                             None             None   
4                                             None  33전 (1/1/1/5/2)   
..                                             ...              ...   
295                                           None             None   
296  단승 : 100.0%      복승 : 100.0%      연승 : 100.0%             None   
297     단승 : 12.7%      복승 : 23.6%      연승 : 41.8%             None   
298      단승 : 6.7%      복승 : 20.0%      연승 : 31.1%             None   
299                                           None  16전 (1/1/1/0/1)   

                                       mom_rate  
0       단승 : 0.0%      복승 : 0.0%      연승 : 0.0%  
1                                          None  
2    단승 : 27.8%      복승 : 50.0%      연승 : 61.1%  
3                                          None  
4       단승 : 3.0%      복승 : 6.1%      연승 : 9.1%  
..                                          ...  
295                                        None  
296                                        None  
297                                        None  
298                                        None  
299   단승 : 6.3%      복승 : 12.5%      연승 : 18.8%  

[300 rows x 8 columns]

In [46]:
df=pd.DataFrame(data=[data1],index=[0])
df.to_excel('data1.xlsx',index=False)

In [76]:
len(horse_meter)

29

In [3]:
import numpy as np

# 독립 변수 X와 관측된 종속 변수 y를 생성
X = np.array([[1, 2], [2, 3], [3, 4]])
y = np.array([2, 4, 6])

# Hat matrix 계산
X_transpose = np.transpose(X)
XtX_inverse = np.linalg.inv(np.dot(X_transpose, X))
H = np.dot(np.dot(X, XtX_inverse), X_transpose)

print("Hat matrix H:")
print(H)

Hat matrix H:
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
