In [9]:
pip install torch

     -------------------------------------- 192.3/192.3 MB 3.8 MB/s eta 0:00:00
     ---------------------------------------- 1.6/1.6 MB 9.5 MB/s eta 0:00:00
     -------------------------------------- 166.4/166.4 KB 4.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\wjswp\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [13]:
import torch
tensor = torch.randn(3,5)
x_hat=torch.autograd.Variable(tensor,requires_grad=True)
print(tensor)
print(x_hat)

tensor([[-1.9348, -0.5668, -0.2168, -0.9017,  0.4590],
        [ 1.2832,  0.5990,  0.2157,  2.8856, -0.2616],
        [-0.1261,  0.7778,  0.2119,  1.2028,  0.2635]])
tensor([[-1.9348, -0.5668, -0.2168, -0.9017,  0.4590],
        [ 1.2832,  0.5990,  0.2157,  2.8856, -0.2616],
        [-0.1261,  0.7778,  0.2119,  1.2028,  0.2635]], requires_grad=True)


In [19]:
num_epochs = 10000

for epoch in range(num_epochs):
    for _ in range(5):  # Critic updates (as recommended for WGAN)
        # Generate random noise
        z = torch.randn(batch_size, z_dim)
        #batch_size, z_dim 차원의 정규분포를 따르는 랜덤 노이즈를 생성

        # Generate fake data
        fake_data = G(z)
        #랜덤 노이즈를 generator에 집어넣어 가짜 데이터 생성
        # Real data (not shown here: load and preprocess real data)

        # Interpolate between real and fake data for gradient penalty
        epsilon = torch.rand(batch_size, 1)
        # epsilon생성 (추후에 보간법을 이용하여 가짜와 진짜 사이의 x값 생성)
        x_hat = epsilon * real_data + (1 - epsilon) * fake_data
        #보간법을 이용한 x값 생성
        x_hat = torch.autograd.Variable(x_hat, requires_grad=True)
        #autograd.Variable를 통해 x_hat에서의 기울기 값 구함

        # Compute critic scores for interpolated data
        critic_scores_x_hat = D(x_hat)
        #Discriminator에 x_hat를 넣어 critic_scores를 구함

        # Compute gradient penalty
        gradients = torch.autograd.grad(critic_scores_x_hat, x_hat, grad_outputs=torch.ones(critic_scores_x_hat.size()))
        #Discriminator함수를 미분하고, 그 값에 x_hat를 넣겠다
        #torch.ones()를 넣으면, 안에 critic_scores_x_hat.size() 차원의 1행렬이 나옴
        #critic_scores_x_hat차원만큼의 gradient값이 나옴
        gradient_penalty = lambda_gp * ((gradients[0].norm(2, dim=1) - 1) ** 2).mean()
        #gradient_penalty를 구할 것인데, 각 기울기의 norm값에 -1를 한값의 평균에 lambda를 곱함
        #각 행 grad값의 제곱의 합의 제곱근에 1를 뺴고, 제곱한 것의 평균을 구하고 lambda_gp를 곱합


        # Update the discriminator
        D_loss = -torch.mean(D(real_data)) + torch.mean(D(fake_data)) + gradient_penalty
        D.zero_grad()
        D_loss.backward()
        D_optimizer.step()

    # Generate new random noise
    z = torch.randn(batch_size, z_dim)

    # Generate fake data
    fake_data = G(z)

    # Update the generator
    G_loss = -torch.mean(D(fake_data))
    G.zero_grad()
    G_loss.backward()
    G_optimizer.step()

    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch [{epoch}/{num_epochs}] | D_loss: {D_loss.item()} | G_loss: {G_loss.item()}")






RuntimeError: grad can be implicitly created only for scalar outputs

In [40]:
#gradients = torch.autograd.grad(critic_scores_x_hat, x_hat, grad_outputs=torch.ones(critic_scores_x_hat.size()))
input=torch.tensor([[3.0,2.0,3.0],[1.0,2.0,3.0]],requires_grad=True)
output=2*input**3+2*input**2
grads=torch.autograd.grad(output,input,grad_outputs=torch.ones(output.size()))
gradient_penalty = 10 * ((grads[0].norm(2, dim=1) - 1) ** 2).mean()
print(grads[0])
print(gradient_penalty)

tensor([[66., 32., 66.],
        [10., 32., 66.]])
tensor(74363.0234)


97.67117106835208
7436.30301922
tensor([98.6712, 74.0270])
