In [3]:
pip install keyboard

     ---------------------------------------- 58.1/58.1 KB 3.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\wjswp\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [1]:
import keyboard
import time
input_list=[]
time.sleep(1)
input_list.append(keyboard.read_key())
input_list


['d']

In [2]:
import keyboard
import time

# 입력과 누른 시간을 저장할 리스트
input_list = []

# 기록 중인지 여부를 나타내는 변수
recording = False
start_time = 0  # 키를 누른 시간

def toggle_recording(e):
    global recording, start_time

    if e.event_type == keyboard.KEY_DOWN and e.name == 'esc':
        if not recording:
            recording = True
            start_time = time.time()
            print("기록을 시작합니다.")
        else:
            recording = False
            print("기록을 중지합니다.")

keyboard.on_press(toggle_recording)

try:
    while True:
        if recording:
            user_input = keyboard.read_event(suppress=True)
            if user_input.event_type == keyboard.KEY_UP:
                end_time = time.time()
                duration = end_time - start_time
                input_list.append((user_input, duration))
            elif user_input.event_type == keyboard.KEY_DOWN:
                start_time = time.time()
except KeyboardInterrupt:
    pass

keyboard.unhook_all()

# 저장된 입력과 누른 시간을 출력
for entry in input_list:
    event, duration = entry
    print("입력:", event, "누른 시간:", duration, "초")

기록을 시작합니다.


: 

In [1]:
import keyboard
import time

q_pressed_time=None
def on_key_event(e):
    global q_pressed_time
    if e.event_type==keyboard.KEY_DOWN and e.name=='q':
        q_pressed_time=time.perf_counter()
    elif e.event_type == keyboard.KEY_UP and e.name=='q':
        if q_pressed_time is not None:
            release_time=time.perf_counter()
            duration = release_time-q_pressed_time
            print(f"'q' 키를 {duration:.3f}초 동안 눌렀습니다.")

keyboard.hook(on_key_event)

try:
    keyboard.wait('esc')
except KeyboardInterrupt:
    pass

keyboard.unhook_all()

'q' 키를 0.066초 동안 눌렀습니다.
'q' 키를 0.337초 동안 눌렀습니다.
'q' 키를 0.065초 동안 눌렀습니다.
'q' 키를 0.045초 동안 눌렀습니다.
'q' 키를 0.065초 동안 눌렀습니다.
'q' 키를 0.066초 동안 눌렀습니다.
'q' 키를 0.055초 동안 눌렀습니다.
'q' 키를 0.071초 동안 눌렀습니다.


In [3]:
import keyboard
import time
import random

# 각 키의 눌린 시간을 저장하는 딕셔너리
key_pressed_times = {}

def on_key_event(e):
    key = e.name
    current_time = time.perf_counter()

    if e.event_type == keyboard.KEY_DOWN:
        # 키가 눌렸을 때 눌린 시간을 저장
        key_pressed_times[key] = current_time
    elif e.event_type == keyboard.KEY_UP:
        # 키가 떼졌을 때 눌린 시간을 계산하고 출력
        if key in key_pressed_times:
            duration = current_time - key_pressed_times[key]
            print(f"'{key}' 키를 {duration:.3f} 초 동안 눌렀습니다.")
            del key_pressed_times[key]

keyboard.hook(on_key_event)

try:
    keyboard.wait('esc')  # 'esc' 키를 누를 때까지 실행
except KeyboardInterrupt:
    pass

keyboard.unhook_all()




's' 키를 0.227 초 동안 눌렀습니다.
'd' 키를 0.207 초 동안 눌렀습니다.
'k' 키를 0.101 초 동안 눌렀습니다.
'k' 키를 0.116 초 동안 눌렀습니다.
'right alt' 키를 0.161 초 동안 눌렀습니다.
's' 키를 0.106 초 동안 눌렀습니다.
'k' 키를 0.111 초 동안 눌렀습니다.
's' 키를 0.090 초 동안 눌렀습니다.
'm' 키를 0.162 초 동안 눌렀습니다.
's' 키를 0.107 초 동안 눌렀습니다.
'space' 키를 0.151 초 동안 눌렀습니다.
'q' 키를 0.121 초 동안 눌렀습니다.
'o' 키를 0.141 초 동안 눌렀습니다.
'q' 키를 0.161 초 동안 눌렀습니다.
'k' 키를 0.171 초 동안 눌렀습니다.
'd' 키를 0.111 초 동안 눌렀습니다.
'l' 키를 0.161 초 동안 눌렀습니다.
'q' 키를 0.111 초 동안 눌렀습니다.
's' 키를 0.136 초 동안 눌렀습니다.
'l' 키를 0.171 초 동안 눌렀습니다.
'e' 키를 0.125 초 동안 눌렀습니다.
'k' 키를 0.147 초 동안 눌렀습니다.
'space' 키를 0.121 초 동안 눌렀습니다.
'r' 키를 0.085 초 동안 눌렀습니다.
'n' 키를 0.121 초 동안 눌렀습니다.
't' 키를 0.095 초 동안 눌렀습니다.


In [19]:
import keyboard
import time
import random

# 각 키의 눌린 시간을 저장하는 딕셔너리
key_pressed_times = {}

# 눌린 키와 눌린 시간을 저장할 벡터
key_total=[]
key_count=[]

def on_key_event(e):
    key = e.name
    current_time = time.perf_counter()
    if e.event_type == keyboard.KEY_DOWN:
        # 키가 눌렸을 때 눌린 키와 눌린 시간을 저장
        key_count.append(key)
        key_pressed_times[key] = current_time
    elif e.event_type == keyboard.KEY_UP:
        # 키가 떼졌을 때 눌린 시간을 계산하고 출력
        if key in key_pressed_times:
            duration = current_time - key_pressed_times[key]
            key_count.append(duration)
            key_total.append(key_count)
            del key_pressed_times[key]
            key_count=[]

keyboard.hook(on_key_event)

try:
    keyboard.wait('esc')  # 'esc' 키를 누를 때까지 실행
except KeyboardInterrupt:
    pass

keyboard.unhook_all()


Traceback (most recent call last):
  File "c:\Users\wjswp\AppData\Local\Programs\Python\Python310\lib\site-packages\keyboard\_generic.py", line 22, in invoke_handlers
    if handler(event):
  File "C:\Users\wjswp\AppData\Local\Temp\ipykernel_40064\3528886461.py", line 17, in on_key_event
    key_count.append(key)
UnboundLocalError: local variable 'key_count' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\wjswp\AppData\Local\Programs\Python\Python310\lib\site-packages\keyboard\_generic.py", line 22, in invoke_handlers
    if handler(event):
  File "C:\Users\wjswp\AppData\Local\Temp\ipykernel_40064\3528886461.py", line 17, in on_key_event
    key_count.append(key)
UnboundLocalError: local variable 'key_count' referenced before assignment
Traceback (most recent call last):
  File "c:\Users\wjswp\AppData\Local\Programs\Python\Python310\lib\site-packages\keyboard\_generic.py", line 22, in invoke_handlers
    if handler(event):
  File "C:\Users\wjswp\AppData

In [46]:
import numpy as np
#M은 Q라고 생각하면됨

fac = np.array([0.1, 0.2, 0.4, 0.2, 0.1])
center = np.array([ 0.05 , 0.05 , 0.2 , 0.3 , 0.4 ]) 
M1 = np.array([[ 0 , 1 , 2 , 3 , 4 ], 
              [ 1 , 0 , 1 , 2 , 3 ], 
              [ 2 , 1 , 0 , 1 , 2 ], [
               3 , 2 , 1 , 0 , 1 ] , 
              [ 4 , 3 , 2 , 1 , 0 ] ])
print(M1[0])

[0 1 2 3 4]


In [47]:
def own_sinkhorn(a,b,reg,M)
    K=np.exp(-M/M.max()/reg)
    nit=100
    u=np.ones((len(a),))

    for i in ragne(1,nit):
        v=b/np.dot(K.T,u)
        u=a/(np.dot(K,v))

NameError: name 'KT' is not defined

In [51]:
print((-M1/M1.max()/0.1).T)
print(np.ones((len(fac),)))

[[  0.   -2.5  -5.   -7.5 -10. ]
 [ -2.5   0.   -2.5  -5.   -7.5]
 [ -5.   -2.5   0.   -2.5  -5. ]
 [ -7.5  -5.   -2.5   0.   -2.5]
 [-10.   -7.5  -5.   -2.5   0. ]]
[1. 1. 1. 1. 1.]
